FROM golang:1.24.2-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /migrator ./cmd/migrator/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /migrator .
COPY migrations /app/migrations
COPY config/example.yml ./config/config.yml

CMD ["./migrator", "-command", "up"]