env: "dev"

kafka:
  brokers:
    - kafka:9092
  group_id: notification-group
  topics:
    - user-notifications
    - post-notifications

database:
  username: "postgres"
  password: "admin"
  host: "notification-db"
  port: "5435"
  db_name: "notificationservice"
  migrations_path: "./migrations"

